//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountDetailsPrinter
    {
        public int ID { get; set; }
        public string AccountHolderName { get; set; }
        public string BankAccountNumber { get; set; }
        public string Branch { get; set; }
        public string IFSC { get; set; }
        public string UPI { get; set; }
        public string PAN { get; set; }
        public Nullable<int> PrinterId { get; set; }
        public string RazorPayRefId { get; set; }
    
        public virtual Printer Printer { get; set; }
    }
}
