//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Meetings = new HashSet<Meeting>();
            this.Transactions = new HashSet<Transaction>();
            this.Orders = new HashSet<Order>();
            this.AddressUsers = new HashSet<AddressUser>();
        }
    
        public int userId { get; set; }
        public string registrationId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string photolink { get; set; }
        public string userName { get; set; }
        public string emailId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string city { get; set; }
        public string dateOfBirth { get; set; }
        public string experience { get; set; }
        public string gender { get; set; }
        public string mobileNumber { get; set; }
        public string postalCode { get; set; }
        public string profileUrl { get; set; }
        public string state { get; set; }
        public string verifyEmal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressUser> AddressUsers { get; set; }
    }
}
