//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string meetingId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> designerId { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string meetingLink { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<System.DateTime> meetingTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Designer Designer { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
