//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mLearnDBEntities : DbContext
    {
        public mLearnDBEntities()
            : base("name=mLearnDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<CourseDetail> CourseDetails { get; set; }
        public virtual DbSet<mLearnTopic> mLearnTopics { get; set; }
        public virtual DbSet<RegisterdCourse> RegisterdCourses { get; set; }
        public virtual DbSet<TrainerCourseMapping> TrainerCourseMappings { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<GuestLogin> GuestLogins { get; set; }
        public virtual DbSet<UserFeedback> UserFeedbacks { get; set; }
        public virtual DbSet<PasswordReset> PasswordResets { get; set; }
        public virtual DbSet<StoreAPIToken> StoreAPITokens { get; set; }
        public virtual DbSet<AddressPrinter> AddressPrinters { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Designer> Designers { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ServiceablePinCode> ServiceablePinCodes { get; set; }
        public virtual DbSet<PrintPrcQuantity> PrintPrcQuantities { get; set; }
        public virtual DbSet<MasterFlag> MasterFlags { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<NotificationDesigner> NotificationDesigners { get; set; }
        public virtual DbSet<Notificationprnter> Notificationprnters { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<BankAccountDetailsDesigner> BankAccountDetailsDesigners { get; set; }
        public virtual DbSet<BankAccountDetailsPrinter> BankAccountDetailsPrinters { get; set; }
        public virtual DbSet<TransactionsPAYOUT> TransactionsPAYOUTs { get; set; }
        public virtual DbSet<AddressUser> AddressUsers { get; set; }
        public virtual DbSet<UserCart> UserCarts { get; set; }
        public virtual DbSet<orderDetail> orderDetails { get; set; }
        public virtual DbSet<TransactionsVendorFee> TransactionsVendorFees { get; set; }
    }
}
