//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLearnTopic
    {
        public int mLearnId { get; set; }
        public int courseId { get; set; }
        public string topicName { get; set; }
        public string topicId { get; set; }
        public string fees { get; set; }
    
        public virtual CourseDetail CourseDetail { get; set; }
    }
}
