//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderDetail
    {
        public int id { get; set; }
        public Nullable<int> orderid { get; set; }
        public string sourceCodeFilePath { get; set; }
        public string finalDesignFilepath { get; set; }
        public string specifications { get; set; }
        public string content { get; set; }
        public string contentpath { get; set; }
        public Nullable<int> productId { get; set; }
        public string sampleImageLogo { get; set; }
        public string orderType { get; set; }
        public string GSTNumber { get; set; }
        public string BillingName { get; set; }
        public string referenceImageURL { get; set; }
        public string logoprintreadyImageURL { get; set; }
        public string industry { get; set; }
        public string category { get; set; }
        public string subcategory { get; set; }
        public string orientation { get; set; }
        public string size { get; set; }
        public string paperGSM { get; set; }
        public string quantity { get; set; }
        public string pincode { get; set; }
        public Nullable<System.DateTime> meetingTime { get; set; }
        public string meetingDurationMins { get; set; }
        public string Price { get; set; }
        public string GST { get; set; }
        public string Total { get; set; }
        public string BaseDesignPrice { get; set; }
        public string SourceFileFees { get; set; }
        public string ProfessionDesignerFees { get; set; }
        public string DesignGST { get; set; }
        public string PrintGST { get; set; }
        public string TotalDesignCost { get; set; }
        public string TotalPrintCost { get; set; }
        public Nullable<bool> selectedProfDesiner { get; set; }
        public Nullable<bool> selectedSourceFile { get; set; }
        public Nullable<bool> IsDesignCompleted { get; set; }
        public Nullable<bool> IsPrintCompleted { get; set; }
        public Nullable<decimal> designerCost { get; set; }
        public Nullable<decimal> printercost { get; set; }
        public Nullable<decimal> ProfessiondesignerFeesAfterCommision { get; set; }
        public Nullable<bool> IsDesignerFinishedOrder { get; set; }
        public Nullable<bool> isMeetingRescheduledOpted { get; set; }
        public string DeliveryDays { get; set; }
        public Nullable<System.DateTime> UserAcceptanceTime { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
