//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintPrcQuantity
    {
        public int Id { get; set; }
        public Nullable<int> prodDetailsId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> pricePerUnit { get; set; }
        public string deliveryDays { get; set; }
        public Nullable<int> printCommision { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
