//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Printer()
        {
            this.AddressPrinters = new HashSet<AddressPrinter>();
            this.Orders = new HashSet<Order>();
            this.BankAccountDetailsPrinters = new HashSet<BankAccountDetailsPrinter>();
        }
    
        public int userId { get; set; }
        public string registrationId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string photolink { get; set; }
        public string userName { get; set; }
        public string emailId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string gender { get; set; }
        public string dateOfBirth { get; set; }
        public string mobileNumber { get; set; }
        public string profileUrl { get; set; }
        public string location { get; set; }
        public string GST { get; set; }
        public string GSTCertificateURL { get; set; }
        public string verifyEmal { get; set; }
        public string PAN { get; set; }
        public string Aadhar { get; set; }
        public Nullable<bool> IsProfileVerified { get; set; }
        public Nullable<bool> isRegistrationFeesPaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressPrinter> AddressPrinters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankAccountDetailsPrinter> BankAccountDetailsPrinters { get; set; }
    }
}
