//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.PrintPrcQuantities = new HashSet<PrintPrcQuantity>();
        }
    
        public int ProdDetailsId { get; set; }
        public Nullable<int> productId { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public string ProductSize { get; set; }
        public string Orientation { get; set; }
        public string PaperGSM { get; set; }
        public string quantities { get; set; }
        public string productPrice { get; set; }
        public string productDescription { get; set; }
        public Nullable<int> producPreference { get; set; }
        public string productCode { get; set; }
        public Nullable<double> DesignPrice { get; set; }
        public Nullable<double> DesignGST { get; set; }
        public Nullable<double> DesignCommision { get; set; }
        public Nullable<double> PrintPrice { get; set; }
        public Nullable<double> PrintGST { get; set; }
        public Nullable<double> PrintCommision { get; set; }
        public Nullable<int> SlotTimeGap { get; set; }
        public string deliveryTime { get; set; }
        public Nullable<double> deliveryFees { get; set; }
        public Nullable<bool> IsPriceInSqFt { get; set; }
        public Nullable<int> meetingDuration { get; set; }
        public Nullable<double> profDesignerFee { get; set; }
        public Nullable<double> sourceFileFees { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintPrcQuantity> PrintPrcQuantities { get; set; }
    }
}
