//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsVendorFee
    {
        public int id { get; set; }
        public string transactionid { get; set; }
        public string vendorTransactionId { get; set; }
        public Nullable<System.DateTime> transactiondate { get; set; }
        public Nullable<decimal> transactionAmount { get; set; }
        public string transactionStatus { get; set; }
        public string razorPayPaymentId { get; set; }
        public string razorPayOrderId { get; set; }
        public string razorPayRecieptId { get; set; }
        public Nullable<System.DateTime> TransactionCreationDate { get; set; }
        public Nullable<System.DateTime> TransactionUpdateDate { get; set; }
        public string VendorId { get; set; }
        public string VendorType { get; set; }
    }
}
