//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsPAYOUT
    {
        public int TransactionId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> PayOutAmount { get; set; }
        public string razorPayOutID { get; set; }
        public string AccountDeductedfrom { get; set; }
        public string AccountTransferedTo { get; set; }
        public Nullable<decimal> RazorPayFees { get; set; }
        public Nullable<decimal> RazorPayTax { get; set; }
        public string PayOutStatus { get; set; }
        public string PayoutPurpose { get; set; }
        public string PayOutTransactionId { get; set; }
        public string TransactionMode { get; set; }
        public string FailureNote { get; set; }
        public string VendorType { get; set; }
        public Nullable<int> vendorId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
