//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProfile()
        {
            this.RegisterdCourses = new HashSet<RegisterdCourse>();
            this.RegisterdCourses1 = new HashSet<RegisterdCourse>();
            this.TrainerCourseMappings = new HashSet<TrainerCourseMapping>();
            this.Transactions = new HashSet<Transaction>();
            this.UserFeedbacks = new HashSet<UserFeedback>();
        }
    
        public int userId { get; set; }
        public string registrationId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string photolink { get; set; }
        public string userName { get; set; }
        public string emailId { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterdCourse> RegisterdCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisterdCourse> RegisterdCourses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerCourseMapping> TrainerCourseMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFeedback> UserFeedbacks { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual AspNetUser AspNetUser8 { get; set; }
        public virtual AspNetUser AspNetUser9 { get; set; }
        public virtual AspNetUser AspNetUser10 { get; set; }
        public virtual AspNetUser AspNetUser11 { get; set; }
        public virtual AspNetUser AspNetUser12 { get; set; }
        public virtual AspNetUser AspNetUser13 { get; set; }
        public virtual AspNetUser AspNetUser14 { get; set; }
        public virtual AspNetUser AspNetUser15 { get; set; }
        public virtual AspNetUser AspNetUser16 { get; set; }
        public virtual AspNetUser AspNetUser17 { get; set; }
        public virtual AspNetUser AspNetUser18 { get; set; }
        public virtual AspNetUser AspNetUser19 { get; set; }
        public virtual AspNetUser AspNetUser20 { get; set; }
        public virtual AspNetUser AspNetUser21 { get; set; }
        public virtual AspNetUser AspNetUser22 { get; set; }
        public virtual AspNetUser AspNetUser23 { get; set; }
    }
}
