//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mLearnBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCart
    {
        public int CartId { get; set; }
        public string UserEmail { get; set; }
        public string UserCart1 { get; set; }
        public Nullable<bool> IsPrintonly { get; set; }
    }
}
